name: 'Enable SUSFS Kernel Configs'
description: 'Enable SUSFS-related kernel configuration options'

runs:
  using: "composite"
  steps:
    - name: Enable SUSFS Kernel Configs
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          CONFIG_KSU_SUSFS_SUS_MAP=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y